Homework
legeonerkd/Homework pull request #1
Opened 2021-10-18 18:19 UTC by legeonerkd

2021-10-18 18:41 UTC, Flyewzz requested changes

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +    def add_to_tail(self, node: TwoLinkedNode) -> None:
Для добавления в конец есть специальное название **append**

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +        self.tail.next = node
Что произойдет, если в списке не будет ни одного элемента при вызове этого метода?

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +        else:
Можно было вместе **else** поставить в if и elif выше на конце return, а этот else убрать. Тогда у тебя весь код ниже сдвинется на целый Tab (понижаем цикломатическую сложность кода).

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +                elif index == pos and cur.next is None:
Посмотри на это условие и условие if на строке 35. У них первые условия идентичны, их можно объединить в один блок if, а уже внутри него сделать проверку cur.next на None. Если не None, то одно действие, иначе другое.

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +                elif index == pos and cur.next is None:
Что будет, если ни один блок (if / elif) не сработает? Если функция / метод что-то возвращает, они должны что-то возвращать в **любом** случае независимо от того, какой код в ней сработал.
В твоем случае тебе нужно почитать про исключения в Python и узнать, как генерируются ошибки. Подробнее см. [здесь](https://docs.python.org/3/tutorial/errors.html).

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +                    self.add_to_tail(node)
И вообще после успешной процедуры вставки куда-нибудь нет смысла дальше что-то делать, метод можно досрочно завершить, т.к. вставляешь за один вызов метода ты в лучшем случае один новый элемент.

2021-10-18 18:41 UTC, Flyewzz commented on two-linked-list.py
> +# lst.print()
Мертвый код нужно удалить.

2021-10-29 15:08 UTC, legeonerkd commented on two-linked-list.py
> +    def add_to_tail(self, node: TwoLinkedNode) -> None:
fixed

2021-10-29 15:08 UTC, legeonerkd commented on two-linked-list.py
> +        self.tail.next = node
fixed

2021-10-29 15:08 UTC, legeonerkd commented on two-linked-list.py
> +        else:
fixed

2021-10-29 15:09 UTC, legeonerkd commented on two-linked-list.py
> +                elif index == pos and cur.next is None:
fixed

2021-10-29 15:09 UTC, legeonerkd commented on two-linked-list.py
> +                elif index == pos and cur.next is None:
at work

2021-10-29 15:09 UTC, legeonerkd commented on two-linked-list.py
> +                    self.add_to_tail(node)
at work

2021-10-29 15:10 UTC, legeonerkd commented on two-linked-list.py
> +# lst.print()
fixed

2021-11-05 14:33 UTC, legeonerkd commented on two-linked-list.py
> +                    self.add_to_tail(node)
Исправил

2021-11-05 14:43 UTC, legeonerkd commented on two-linked-list.py
> +                elif index == pos and cur.next is None:
Ознакомился, я хотел это сделать при запуске функци. Или лучше в самой функции? И как узнать какие ошибки прописывать?

2021-11-05 15:21 UTC, legeonerkd commented
fixing

2021-11-05 15:21 UTC, merged